[package]
name = "pyo3-litellm"
version = "0.1.0"
edition = "2021"

[dependencies]
common_macros = "0.1.1"
pyo3 = "0.23.4"
pyo3-ffi = "0.23.4"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }


[[bin]]
name = "pyo3"
path = "src/main.rs"


